// Server-side translation utility for Deno runtime

declare const Deno: {
	env: { get(key: string): string | undefined };
	readTextFileSync(path: string): string;
	cwd(): string;
};

interface Translations {
	[key: string]: string;
}

// File reading using Deno
function readFileSync(filePath: string): string | null {
	try {
		return Deno.readTextFileSync(filePath);
	} catch {
		return null;
	}
}

// Path join helper
function joinPath(...segments: string[]): string {
	return segments
		.join('/')
		.replace(/\/+/g, '/')
		.replace(/\/$/, '');
}

// Get current working directory
function getCwd(): string {
	try {
		return Deno.cwd();
	} catch {
		return '/app';
	}
}

// Environment variable access
function getEnv(key: string): string | undefined {
	return Deno.env.get(key);
}

// Cache for loaded translations
let translationsCache: { [lang: string]: Translations } | null = null;

// Server-side translations (subset of full translations for worker use)
const translations: { [lang: string]: Translations } = {
	en: {
		'tripDetection.autoGenerated':
			'Trip detected from location patterns: {locationCount} location{plural} visited',
		'tripDetection.tripAwayFromHome': 'Trip away from home',
		'tripDetection.tripToCity': 'Trip to {city}',
		'tripDetection.tripToCountry': 'Trip to {country}',
		'tripDetection.tripToMultipleCities': 'Trip to {cities}',
		'tripDetection.tripToMultipleCountries': 'Trip to {countries}'
	},
	nl: {
		'tripDetection.autoGenerated':
			'Reis gedetecteerd uit locatiepatronen: {locationCount} locatie{plural} bezocht',
		'tripDetection.tripAwayFromHome': 'Reis weg van huis',
		'tripDetection.tripToCity': 'Reis naar {city}',
		'tripDetection.tripToCountry': 'Reis naar {country}',
		'tripDetection.tripToMultipleCities': 'Reis naar {cities}',
		'tripDetection.tripToMultipleCountries': 'Reis naar {countries}'
	}
};

/**
 * Load full translations from JSON files (used for country names)
 */
function loadFullTranslations(): { [lang: string]: Translations } {
	if (translationsCache) {
		return translationsCache;
	}

	try {
		const languages = ['en', 'nl', 'es'];
		const result: { [lang: string]: Translations } = {};
		const cwd = getCwd();

		for (const lang of languages) {
			const possiblePaths = [
				joinPath(cwd, 'build', 'messages', `${lang}.json`),
				joinPath(cwd, 'static', 'messages', `${lang}.json`)
			];

			let loaded = false;
			for (const filePath of possiblePaths) {
				const fileContent = readFileSync(filePath);
				if (fileContent) {
					result[lang] = JSON.parse(fileContent);
					loaded = true;
					break;
				}
			}

			if (!loaded) {
				console.warn(`Could not load translations for language: ${lang}`);
			}
		}

		translationsCache = result;
		return result;
	} catch (error) {
		console.error('Error loading translations:', error);
		return {};
	}
}

/**
 * Simple server-side translation function for worker environments
 */
export function translateServer(
	key: string,
	params: { [key: string]: string | number } = {},
	language: string = 'en'
): string {
	const lang = translations[language] ? language : 'en';
	const template = translations[lang][key] || translations['en'][key] || key;

	let result = template;
	for (const [paramKey, paramValue] of Object.entries(params)) {
		const placeholder = `{${paramKey}}`;
		result = result.replace(
			new RegExp(placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'),
			paramValue.toString()
		);
	}

	if (getEnv('NODE_ENV') !== 'production') {
		console.log('[translateServer]', { key, template, params, result });
	}
	return result;
}

/**
 * Get plural suffix for location count in different languages
 */
export function getPluralSuffix(count: number, language: string = 'en'): string {
	if (count === 1) return '';

	switch (language) {
		case 'en':
			return 's';
		case 'nl':
			return 's';
		default:
			return 's';
	}
}

/**
 * Get country name from country code for server-side use
 */
export function getCountryNameServer(countryCode: string, language: string = 'en'): string {
	if (!countryCode || countryCode.length !== 2) {
		return countryCode;
	}

	const fullTranslations = loadFullTranslations();
	const lang = fullTranslations[language] ? language : 'en';
	const key = `country.${countryCode.toUpperCase()}`;

	if (fullTranslations[lang] && fullTranslations[lang][key]) {
		return fullTranslations[lang][key];
	}

	if (fullTranslations['en'] && fullTranslations['en'][key]) {
		return fullTranslations['en'][key];
	}

	try {
		const regionNames = new Intl.DisplayNames([language, 'en'], { type: 'region' });
		const countryName = regionNames.of(countryCode.toUpperCase());
		if (countryName && countryName !== countryCode.toUpperCase()) {
			return countryName;
		}
	} catch (error) {
		console.error(`Error getting country name for ${countryCode}:`, error);
	}

	return countryCode.toUpperCase();
}
