{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.routeName | default (printf "%s-web" (include "wayli.fullname" .)) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wayli.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
    {{- with .Values.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.httpRoute.annotations .Values.global.annotations }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.httpRoute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    {{- if .name }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- if or .Values.httpRoute.hostname .Values.httpRoute.extraHostnames }}
  hostnames:
    {{- with .Values.httpRoute.hostname }}
    - {{ . | quote }}
    {{- end }}
    {{- range .Values.httpRoute.extraHostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httpRoute.pathType }}
            value: {{ .Values.httpRoute.path }}
      backendRefs:
        - name: {{ include "wayli.fullname" . }}-web
          port: {{ .Values.web.service.port }}
      {{- if .Values.httpRoute.timeouts }}
      timeouts:
        {{- with .Values.httpRoute.timeouts.request }}
        request: {{ . | quote }}
        {{- end }}
        {{- with .Values.httpRoute.timeouts.backendRequest }}
        backendRequest: {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- with .Values.httpRoute.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
